// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject

package main

import (
	"github.com/ncobase/ncore/concurrency/worker"
	"github.com/ncobase/ncore/config"
	"github.com/ncobase/ncore/data"
	"github.com/ncobase/ncore/extension/manager"
	"github.com/ncobase/ncore/logging/logger"
	"github.com/ncobase/ncore/security/jwt"
)

// Injectors from wire.go:

// InitializeApp wires up the main application with all core dependencies.
// Returns the App, a cleanup function, and any initialization error.
//
// The cleanup function should be called when the application shuts down
// to properly release all resources (database connections, etc.).
//
// Usage:
//
//	app, cleanup, err := InitializeApp()
//	if err != nil {
//	    log.Fatal(err)
//	}
//	defer cleanup()
//	// Use app...
func InitializeApp() (*App, func(), error) {
	configConfig, err := config.GetConfig()
	if err != nil {
		return nil, nil, err
	}
	config2 := config.ProvideLoggerConfig(configConfig)
	loggerLogger, cleanup, err := logger.ProvideLogger(config2)
	if err != nil {
		return nil, nil, err
	}
	config3 := config.ProvideDataConfig(configConfig)
	dataData, cleanup2, err := data.ProvideData(config3)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	managerManager, cleanup3, err := manager.ProvideManager(configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(configConfig, loggerLogger, dataData, managerManager)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitializeTokenManager creates a JWT TokenManager with configuration.
// This is useful when you only need JWT functionality without the full app.
func InitializeTokenManager() (*jwt.TokenManager, error) {
	configConfig, err := config.GetConfig()
	if err != nil {
		return nil, err
	}
	auth := config.ProvideAuthConfig(configConfig)
	jwtConfig := ProvideJWTConfig(auth)
	tokenManager := jwt.ProvideTokenManager(jwtConfig)
	return tokenManager, nil
}

// InitializeWorkerPool creates a worker pool with default configuration.
// Returns the pool, a cleanup function that gracefully stops workers, and any error.
func InitializeWorkerPool() (*worker.Pool, func(), error) {
	workerConfig := ProvideDefaultWorkerConfig()
	pool, cleanup, err := worker.ProvidePool(workerConfig)
	if err != nil {
		return nil, nil, err
	}
	return pool, func() {
		cleanup()
	}, nil
}

// InitializeCustomWorkerPool creates a worker pool with custom configuration.
func InitializeCustomWorkerPool(customCfg *CustomWorkerConfig) (*worker.Pool, func(), error) {
	workerConfig := ProvideWorkerConfigFromCustom(customCfg)
	pool, cleanup, err := worker.ProvidePool(workerConfig)
	if err != nil {
		return nil, nil, err
	}
	return pool, func() {
		cleanup()
	}, nil
}
